spring:
  mqtt:
    enable: true
    url: tcp://broker.emqx.io
    username:
    password:
    consumerclientid: clientid12342312212_c
    # 自定义编码消费者id
    userconsumerclientid: clientid12342312212_d
    timeout: 5000
    # 心跳时间
    keepalive: 2
    # mqtt-topic
    producertopic: bstes,user
    consumertopic: bstes